@startuml domain-model
Flixxic *--> User: "1..*"
Flixxic *--> Content: "1..*"

User <|-- NormalUser: "1..*"
User <|-right- AdminUser: "1..*"

NormalUser -right-> ManagementProfile
AdminUser -up-> ManagementContent

Content <|-- Movie: "1..*"
Content <|-up- Serie: "1..*"
Content *--> Cast: "1..1"
Content o--> Comment: "0..*"
Content *-left-> Trailer: "1..1"    
Content *-right-> Storyline: "1..1"
Content *-up-> Genre: "1..*"
Content o--> Review: "0..*"

Cast *--> Actor: "1..*"

Actor o--> Movie: "1..*"
Actor o--> Serie: "1..*"

Serie *--> Season: "1..*"

Season *--> Episode: "1..*"

Episode o--> Comment: "0..*"
Episode o--> Review: "0..*"
Episode o--> Cast: "1..1"

Comment o--> Reply: "0..*"
Comment o--> LikeOrDislike: "0..*"
@enduml
