@startuml use-cases-context
[*] --> CONTENT_MANAGEMENT
note on link
  Authenticaction
end note

CONTENT_MANAGEMENT --> VIEW_CATALOG
CONTENT_MANAGEMENT --> ADD_CONTENT
CONTENT_MANAGEMENT --> EDIT_CONTENT
CONTENT_MANAGEMENT --> DELETE_CONTENT
CONTENT_MANAGEMENT --> VIEW_CONTENT
CONTENT_MANAGEMENT --> SEARCH_FILTER_CONTENT

VIEW_CATALOG --> [*]
note on link
  Logout
end note
ADD_CONTENT --> [*]
note on link
  Logout
end note
EDIT_CONTENT --> [*]
note on link
  Logout
end note
DELETE_CONTENT --> [*]
note on link
  Logout
end note
VIEW_CONTENT --> [*]
note on link
  Logout
end note
SEARCH_FILTER_CONTENT --> [*]
note on link
  Logout
end note
@enduml

@startuml use-cases-context-v2

[*] --> AUTHENTICATION
AUTHENTICATION --> OPENED_FLIXXIC
note on link 
    Login
end note

OPENED_FLIXXIC -left-> CONTENT_MANAGEMENT
note left    
    * Add new content
    * Edit content
    * Delete content
    * Search and filter content
end note

state continueManagement <<choice>>

OPENED_FLIXXIC --> continueManagement
CONTENT_MANAGEMENT --> continueManagement
continueManagement --> OPENED_FLIXXIC
continueManagement --> [*]
note on link 
    Logout
end note
@enduml